### ISSUE TITLE
What do i have to include here CONFIG = yaml.load(open('./CONFIG.yml'))

### ISSUE THREAD

**Issue by Michael5466** [sshashank124/crypto_rsi_tracker#1]
What do i have to include here CONFIG = yaml.load(open('./CONFIG.yml')) ?
What link/folder path has to be used?

**Comment by sshashank124** [comment]
You need to have a file called `CONFIG.yml` in the same directory as this script. The contents of the file need to be as follows:

``` yml
binance_api:
  key: ...
  secret: ...

gmail:
  user: ...
  password: ...
```

For the `binance_api` `key` and `secret`, you have to create an API key from your Binance account and supply those values in the corresponding fields. The gmail part is optional. If you do not wish to receive the emails, just comment out the relevant parts of the code and just put random values for those fields
